# Generated by Django 3.2.25 on 2024-12-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_communities_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities',
            new_name='Communitie',
        ),
    ]
